### ISSUE TITLE
Apple private API in framework

### ISSUE THREAD

**Issue by tswing** [TuneOSS/cocoapod2.0#2]
Hi~ There.

Apple rejected for my app because My App is using private API.
I reported from apple. 

Finally I found acitivateApp method in Tune.framework.

Could you please solve this problem?

Thanks in advanced.

----------- From Apple ---------
Your app uses or references the following non-public APIs:

activateApp

The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

Next Steps

Please revise your app to remove any non-public APIs. If you have defined methods in your source code with the same names as the above-mentioned APIs, we suggest altering your method names so that they no longer collide with Apple's private APIs to avoid your application being flagged in future submissions.

Additionally, if you are using third party libraries, please update to the most recent version of those libraries. If you do not have access to the libraries' source, you may be able to search the compiled binary using the "strings" or "otool" command line tools. The "strings" tool can output a list of the methods that the library calls and "otool -ov" will output the Objective-C class structures and their defined methods. These tools can help you narrow down where the problematic code resides. You could also use the "nm" tool to verify if any third-party libraries are calling these APIs.

**Comment by harshal-hasoffers** [comment]
The `activateApp` selector reference is in relation to the optional Facebook SDK framework, and not in relation to any private Apple framework. Since FB framework is optional, the TUNE SDK dynamically checks if the FB framework exists. You can find the open source code here: https://github.com/MobileAppTracking/sdk-release/blob/master/sdk-ios/Tune/Tune/TuneFBBridge.m#L105

Please let us know if this explanation is enough to get your app submission unblocked. Meanwhile we will try to replace the `activateApp` selector reference with split strings, so that it won't show up in the strings/otool checks.

**Comment by harshal-hasoffers** [comment]
v4.9.0 is now released.
